// <auto-generated />
namespace Crm_v10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitalCrmv10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalCrmv10));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161314588_InitalCrmv10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
